apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      serviceAccountName: masaruz # Reference below
      containers:
      - name: manager
        image: masaruz/manager:0.0.3
---
apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  type: NodePort
  selector:
    app: manager
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30002
---
# Create service account to give the permission
apiVersion: v1
kind: ServiceAccount
metadata:
  name: masaruz
  namespace: default
---
# Subject role to service account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: masaruz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: masaruz
    namespace: default