apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matchmaker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: matchmaker
    spec:
      containers:
      - name: matchmaker
        image: masaruz/matchmaker:0.0.2
---
kind: Service
apiVersion: v1
metadata:
  name: matchmaker
spec:
  type: NodePort
  selector:
    app: matchmaker
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
    nodePort: 30001